apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: flask-secret
data:
  config.json: ewogICAgIk1ZU1FMX0hPU1QiOiJteXNxbC1zdmMiLAogICAgIk1ZU1FMX1VTRVIiOiAicm9vdCIsCiAgICAiTVlTUUxfUEFTU1dPUkQiOiJwcm9kLXBhc3N3MHJkIiwKICAgICJNWVNRTF9EQiI6ImJsb2dzIgp9
